name: release

on:
  release:
    types:
      - created

jobs:
  release:
    name: release x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: rust-build/rust-build.action@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: x86_64-unknown-linux-musl
